apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: atlas-deployment
spec:
  selector:
    matchLabels:
      app: atlas
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: atlas
    spec:
      containers:
        - name: atlas
          image: sburn/apache-atlas
          ports:
            - containerPort: 21000
          command: ["/opt/apache-atlas-2.0.0/bin/atlas_start.py"]
---
apiVersion: v1
kind: Service
metadata:
  name: atlas-service
spec:
  selector:
    app: atlas
  ports:
    - protocol: TCP
      port: 21000
      targetPort: 21000